# Site settings
title: JHSOI
description: description
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: JHSOI
user_description: The invitational will be held on Februrary 5th, 2022.
user_title: Johns Hopkins Science Olympiad Invitational
email: jhso.invite@gmail.com
twitter_username: scilympiad.com/jhsoi
github_username:  github_username
gplus_username:  jhsoi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
